deco-cx/chat

apps/web/src/components/settings/index.tsx
apps/web/src/components/settings/integrations/index.tsx

feat: improve edit agent ux

---

README.md
apps/web/src/components/chat/Chat.tsx
apps/web/src/components/chat/ChatInput.tsx
apps/web/src/components/chat/tools/Preview.tsx
apps/web/src/components/chat/utils/preview.ts
packages/sdk/src/constants.ts

- fix: attachments positioning
- fix: preview not opening inline (chat)
- feat: automatically open preview

fix: some ui fixes

---

apps/web/src/components/chat/Chat.tsx
apps/web/src/components/chat/EmptyState.tsx
apps/web/src/components/chat/Header.tsx
apps/web/src/components/chat/index.tsx

chore: ui improvements for team agent

---

apps/web/src/components/chat/Chat.tsx
apps/web/src/components/chat/ChatInput.tsx
apps/web/src/components/chat/EmptyState.tsx
apps/web/src/components/chat/Header.tsx
apps/web/src/components/chat/index.tsx
apps/web/src/components/sidebar/index.tsx
packages/sdk/src/crud/mcp.ts
packages/sdk/src/hooks/agent.ts
packages/sdk/src/hooks/mcp.ts

Also, it makes some improvements to:
1. Do not retry on 404 on both agenst and integrations
2. Display deleted agents

chore: display all threads

---

apps/web/src/polyfills.ts

change how we deal with polifyill

---

apps/web/src/components/agents/list.tsx
apps/web/src/components/chat/Chat.tsx
apps/web/src/components/chat/ChatInput.tsx
apps/web/src/components/settings/index.tsx
apps/web/src/components/settings/integrations/schema-display.tsx
packages/sdk/src/constants.ts
packages/sdk/src/crud/agent.ts
packages/sdk/src/models/agent.ts
packages/ui/src/components/select.tsx

openrouter - multi model

---

apps/web/src/components/threads/index.tsx

fix: sort threads

---

apps/web/src/components/settings/index.tsx
apps/web/src/components/settings/integrations/header.tsx
apps/web/src/components/settings/integrations/icon.tsx
apps/web/src/components/settings/integrations/index.tsx

UI fixes for Integrations + remove console

---

apps/web/src/components/chat/index.tsx
apps/web/src/components/settings/integrations/header.tsx
apps/web/src/components/settings/integrations/icon.tsx
apps/web/src/components/settings/integrations/index.tsx

this code has been moved to the api

chore: remove unecessary code

---

apps/web/src/components/agent/index.tsx
apps/web/src/components/chat/Header.tsx

chat header was misaligned within 4px. This fixes this issue

fix chat-header missing pixels

---

apps/web/src/components/agent/index.tsx

Use scrollarea on dock pannels

chore: use scrollarea on pannels

---

apps/web/src/components/chat/ChatInput.tsx

fix(ChatInput): always have a selectedModel

---

apps/web/src/components/agents/hooks.ts
apps/web/src/components/chat/Chat.tsx
apps/web/src/components/integrations/detail/form.tsx
apps/web/src/components/integrations/explorerAgent.md
apps/web/src/components/integrations/list/installed.tsx
apps/web/src/components/integrations/list/marketplace.tsx
apps/web/src/components/integrations/list/useCreateExplorerAgent.ts
apps/web/src/components/settings/integrations/description.tsx
apps/web/src/components/settings/integrations/index.tsx
apps/web/src/components/threads/index.tsx
packages/sdk/src/hooks/mcp.ts
packages/sdk/src/hooks/tools.ts

https://www.loom.com/share/83a96f9d23e545049686b46c3e4569c1

Explorer Agent + UI improvements

---

apps/web/src/components/agent/index.tsx

fix: preview sizing

---

apps/web/src/components/sidebar/index.tsx
packages/sdk/src/crud/thread.ts
packages/sdk/src/hooks/agent.ts

chore: update thread listing to match new API

---

packages/sdk/src/constants.ts

chore: add gpt-4.1

---

apps/web/src/components/chat/Chat.tsx

Feat: Add disclaimer memory on chat

Feat: Add disclaimer memory on chat

---

apps/web/src/components/chat/ChatInput.tsx
apps/web/src/components/chat/ModelSelector.tsx

fix(ui): make model selector a drawer on mobile

---

apps/web/src/components/chat/Chat.tsx
apps/web/src/components/chat/ChatError.tsx
apps/web/src/components/sidebar/header.tsx
apps/web/src/components/wallet/index.tsx
apps/web/src/main.tsx
packages/sdk/src/crud/wallet.ts
packages/sdk/src/index.ts

**Add Wallet UI and Error Handling to Chat Application**
- **Wallet Page & UI**
- Introduced a new `/wallet` route and page for users to view their balance, transaction history, and add credits.
- Implemented wallet components with support for viewing activity, transaction details, and adding funds via a dialog.
- Added currency formatting, input validation, and minimum deposit enforcement.
- **Chat Error Handling**
- Refactored chat error display into a new `ChatError` component.
- Improved error messages for insufficient funds, including a direct link to the wallet page to add credits.
- Tracked insufficient funds errors via analytics events.
- **Sidebar & Navigation**
- Added a "Wallet" link to the sidebar dropdown for easy access.
- **SDK & API Integration**
- Added wallet CRUD …

feat: add user wallet

---

apps/web/src/components/wallet/index.tsx
apps/web/src/hooks/useIncomingUrlAlert.ts

when redirected from stripe with some alert on the querystring, show it like this:

fix: handle url alert from stripe redirects

---

apps/web/src/components/chat/Chat.tsx

Changed the scroll behavior: now, when the chat is streaming, the user can scroll freely. However, if the user is focused at the bottom while the chat is streaming, the scroll will automatically follow the stream.

Improving chat scroll

---

packages/sdk/src/constants.ts

feat: add grok 3 beta to models

---

apps/web/src/components/chat/Chat.tsx
apps/web/src/components/wallet/index.tsx

fix: first message chat errors + update wallet deposit min amount

---

packages/sdk/LICENSE
packages/sdk/README.md
packages/sdk/jsr.json
packages/sdk/package.json

Publishing deco chat SDK  on JSR. 
1. Adding a license to the package
2. Adding a README to the package
3. Adding jsr.json

Publishing SDK on JSR

---

apps/web/src/components/agents/list.tsx

fix: improve agent card

---

apps/web/src/components/agent/preview.tsx
apps/web/src/components/chat/Chat.tsx
apps/web/src/components/chat/tools/Preview.tsx
apps/web/src/components/chat/utils/preview.ts

It's impossible to deal with images 😵‍💫

feat: improve image preview ux

---

apps/web/src/components/chat/Chat.tsx

Feat: Remove memory limit message

Feat: Remove memory limit message

---

apps/web/src/components/agent/index.tsx
apps/web/src/components/chat/Chat.tsx
apps/web/src/components/chat/ToolMessage.tsx
apps/web/src/components/chat/index.tsx
apps/web/src/components/integrations/detail/form.tsx
apps/web/src/components/integrations/list/useCreateExplorerAgent.ts
apps/web/src/components/settings/index.tsx
packages/sdk/src/crud/mcp.ts
packages/sdk/src/hooks/agent.ts
packages/sdk/src/hooks/tools.ts
packages/sdk/src/models/mcp.ts

Feat: Add Handoff view
Now we receive from api the list of tools, agents and core integrations
https://github.com/user-attachments/assets/db063d03-e07d-4176-ae77-1880ee9533b1

Feat: Add Handoff view

---

apps/web/src/components/chat/Chat.tsx
apps/web/src/components/chat/ChatInput.tsx
apps/web/src/components/chat/ModelSelector.tsx
packages/sdk/src/constants.ts

Now that the api supports passing model per request in a stateless way i can do this.

feat: keep model in localstorage and make the selector instant

---

apps/web/src/components/about/CTA.tsx
apps/web/src/components/about/Hero.tsx
apps/web/src/components/login/index.tsx

feat: track landing events

---

apps/web/src/components/sidebar/footer.tsx
apps/web/src/components/sidebar/index.tsx
apps/web/src/components/wallet/index.tsx

feat: wallet events

---

apps/web/src/components/agent/preview.tsx
packages/sdk/src/crud/user.ts
packages/sdk/src/index.ts

feat: get user to api

---

apps/web/package.json
apps/web/src/components/settings/index.tsx
apps/web/src/components/settings/integrations/header.tsx
apps/web/src/components/settings/integrations/index.tsx
packages/sdk/package.json
packages/sdk/src/hooks/store.tsx
packages/sdk/src/models/agent.ts
packages/ui/package.json

chore: use form tools and simplify agent form

---

apps/web/src/components/integrations/list/common.tsx
apps/web/src/components/integrations/list/installed.tsx
apps/web/src/components/integrations/list/marketplace.tsx

Improve card icons for integrations

chore: Integration image cards

---

apps/web/src/components/chat/Chat.tsx

tries simplifying auto scroll by using intersection observer

chore: simplify autoscroll

---

apps/web/src/components/chat/ModelSelector.tsx
apps/web/src/components/sidebar/footer.tsx
packages/ui/package.json
packages/ui/src/components/responsive-dropdown.tsx
packages/ui/src/components/responsive-select.tsx

Automatic way to have:
- drawer on mobile
- select/dropdown on desktop
so making nice mobile UX is the default

feat: enforce a nicer mobile ux with new components - responsive Select/Dropdown

---

apps/web/src/components/agents/list.tsx
apps/web/src/components/chat/context.tsx
apps/web/src/components/integrations/detail/edit.tsx
apps/web/src/components/integrations/list/breadcrumb.tsx
apps/web/src/components/integrations/list/installed.tsx
apps/web/src/components/integrations/list/marketplace.tsx
packages/sdk/src/constants.ts
packages/sdk/src/crud/agent.ts
packages/sdk/src/crud/mcp.ts
packages/sdk/src/crud/thread.ts
packages/sdk/src/hooks/agent.ts
packages/sdk/src/hooks/mcp.ts
packages/sdk/src/hooks/thread.ts

Multiple validations/invalidations improvements to speedup ui navigations and crud operations

improve query validations and invalidations

---

apps/web/src/main.tsx

Add suspense + spinner to every route entrypoint

feat: suspense at route entrypoints

---

apps/web/src/components/chat/tools/Preview.tsx

- Updated image source handling to utilize the URL object for better pathname validation.
- Ensured consistent usage of the URL object for src attributes in ImagePreview and ImageDialog components.

Refactor Preview component to use URL object for image source validation

---

apps/web/src/components/agents/list.tsx

chore: agent card click goes to edit

---

apps/web/src/components/chat/ToolMessage.tsx

- make the clickable area be the whole thing when only one tool call was made.
- make the clickable thing be bigger when more than one tool call was made. 
- make the clickable thing change bg on hover.
- once you open a tool detail, smooth scroll the content into view.

improve(chat-messages): better tool messages ux

---

packages/sdk/src/constants.ts
packages/sdk/src/crud/agent.ts
packages/sdk/src/crud/fs.tsx
packages/sdk/src/crud/mcp.ts
packages/sdk/src/crud/thread.ts
packages/sdk/src/crud/user.ts
packages/sdk/src/crud/wallet.ts
packages/sdk/src/fetcher.ts
packages/sdk/src/stub.ts

Revert "Revert "feat: standardize fetch and instrument with trace debug id""

---

apps/web/index.css
apps/web/src/components/chat/Message.tsx
apps/web/src/components/settings/agent.tsx

Click to create agent:
crazy link:

fix(ui): overflowing agent form inputs and text messages

---

apps/web/src/components/agents/list.tsx

New chat button on dropdown agent

feat: add new chat button on agents

---

apps/web/src/components/chat/ToolMessage.tsx

Add copy button for tool results.
Closes #141

feat: add copy button for tool results

---

apps/web/src/components/chat/tools/Preview.tsx

Add a skeleton on image load
Closes #145

fix: add image loading state

---

apps/api/package.json
packages/sdk/src/hooks/tools.ts

hotfix tools listing

---

apps/web/src/components/sidebar/footer.tsx
apps/web/src/hooks/data/useUser.ts
packages/sdk/src/crud/user.ts

Fixes redirect to login flow from this PR https://github.com/deco-cx/chat/pull/156

fix: redirect to login when unauthorized

---

apps/api/src/auth/assertions.ts

Allow @deco.cx to access any workspace. This is a WIP and should be removed as soon as we have team joining info for people

fix: Allow deco access

---

apps/web/package.json
apps/web/src/components/triggers/addTriggerModal.tsx
apps/web/src/components/triggers/cronTriggerForm.tsx
apps/web/src/components/triggers/listTriggers.tsx
apps/web/src/components/triggers/triggerDetails.tsx
apps/web/src/components/triggers/webhookTriggerForm.tsx
packages/sdk/src/crud/trigger.ts
packages/sdk/src/hooks/trigger.ts

Feat: Create Trigger UI
https://github.com/user-attachments/assets/822f8c6f-39de-4ff2-b5be-b6b43a0f47b7

Feat: Create Trigger UI

---

apps/web/src/components/chat/ChatMessages.tsx
apps/web/src/components/chat/Message.tsx
apps/web/src/components/chat/Picker.tsx
apps/web/src/components/chat/ToolMessage.tsx

Fix confirm tool breaking the whole thread.

fix: confim tool picker

---

apps/api/src/user/index.ts

drop console log from https://github.com/deco-cx/chat/pull/179

drop console.log from #179

---

apps/web/src/components/triggers/deleteTriggerModal.tsx
apps/web/src/components/triggers/listTriggers.tsx
apps/web/src/components/triggers/triggerCard.tsx
packages/sdk/src/crud/trigger.ts
packages/sdk/src/hooks/trigger.ts

Feat: Add delete trigger UI

---

apps/web/src/components/triggers/addTriggerModal.tsx
apps/web/src/components/triggers/listTriggers.tsx
apps/web/src/components/triggers/webhookTriggerForm.tsx
packages/sdk/src/hooks/trigger.ts

Feat: Create trigger button on list

---

apps/web/src/components/agent/edit.tsx
apps/web/src/components/sidebar/index.tsx
apps/web/src/components/triggers/TriggerCardList.tsx
apps/web/src/components/triggers/TriggerTableList.tsx
apps/web/src/components/triggers/addTriggerModal.tsx
apps/web/src/components/triggers/agentTriggers.tsx
apps/web/src/components/triggers/listTriggers.tsx
apps/web/src/components/triggers/triggerDetails.tsx
apps/web/src/components/triggers/webhookTriggerForm.tsx
apps/web/src/main.tsx
packages/sdk/src/crud/trigger.ts
packages/sdk/src/hooks/trigger.ts

Feat: Add list triggers view
https://github.com/user-attachments/assets/0d49f379-2363-4f17-a4ac-9c1ca3e1b9cf

Feat: Add list triggers view

---

apps/api/src/api/agents/well-known.ts
packages/sdk/src/constants.ts

best friends with sonnet again

---

apps/api/src/utils/convertToUIMessages.ts
apps/web/src/components/audit/AuditFilters.tsx
apps/web/src/components/audit/AuditTable.tsx
apps/web/src/components/audit/detail.tsx
apps/web/src/components/audit/list.tsx
apps/web/src/components/triggers/triggerDetails.tsx

Feat: Add trigger logs

---

apps/api/src/api/threads/api.ts

Prevent throw error trying to query on mastra_threads table

fix: safe execute prevent throw error on THREADS_LIST tool

---

apps/api/src/utils/convertToUIMessages.ts

Improve messages retrieval by improving messages function
A few before/after resutls. 
Look how we:
1. Improved messages/tool call ordering
2. Added reasoning tokens

chore: improve message retrieval

---

packages/ui/src/components/icon.tsx

disable auto translation for icons

fix: disable translations

---

apps/web/src/components/layout.tsx
apps/web/src/components/sidebar/header.tsx
apps/web/src/components/sidebar/settings.tsx
apps/web/src/main.tsx

feat: un peu trop chic

---

apps/web/package.json
apps/web/src/components/chat/LazyHighlighter.tsx
apps/web/src/components/chat/Markdown.tsx
deno.json

added syntax highlighting with prism, a copy button and better ui.
Before:
Now:

better chat code snippet rendering

---

apps/web/src/components/chat/ChatInput.tsx

fix my friend's error

---

apps/web/src/components/chat/AudioButton.tsx

unecessary tailwind

---

apps/api/src/utils/convertToUIMessages.ts
apps/web/src/components/agent/ChatHeader.tsx
apps/web/src/components/agent/DetailHeader.tsx
apps/web/src/components/agent/chat.tsx
apps/web/src/components/agent/edit.tsx
apps/web/src/components/agents/list.tsx
apps/web/src/components/audit/detail.tsx
apps/web/src/components/chat/ChatInput.tsx
apps/web/src/components/chat/EmptyState.tsx
apps/web/src/components/chat/ModelSelector.tsx
apps/web/src/components/chat/ToolMessage.tsx
apps/web/src/components/chat/context.tsx
apps/web/src/components/chat/utils/preview.ts
apps/web/src/components/integrations/detail/edit.tsx
apps/web/src/components/integrations/list/breadcrumb.tsx
apps/web/src/components/layout.tsx
apps/web/src/components/pageLayout.tsx
apps/web/src/components/triggers/addTriggerModal.tsx
apps/web/src/components/triggers/agentTriggers.tsx
apps/web/src/components/triggers/listTriggers.tsx
apps/web/src/components/triggers/triggerDetails.tsx
packages/ui/src/components/button.tsx

Adds muri headers for desktop. More changes for mobile and other faetures are coming

chore: Add muri headers for desktop

---

packages/sdk/src/constants.ts

merge only after backend is ok

update to latest gemini model

---

apps/web/src/components/settings/agent.tsx

chore: update default model on agent form

---

packages/ui/src/components/sidebar.tsx

Fixes sidebar breaking dockview layout.
Before/after

fix: dockview layout

---

apps/web/package.json
apps/web/src/components/sidebar/TeamSelector.tsx
apps/web/src/components/sidebar/header.tsx
apps/web/src/components/sidebar/index.tsx
apps/web/src/main.tsx

This PR implements this specific part of the sidebar

feat: improve naming on routes and bump some deps

---

apps/api/src/api.ts
apps/web/src/components/chat/ChatError.tsx
apps/web/src/components/chat/context.tsx
packages/sdk/src/fetcher.ts

Add copiable correlation id to error banners

feat: add copiable correlation id to error banners

---

apps/web/src/components/integrations/list/installed.tsx
apps/web/src/components/integrations/list/marketplace.tsx

fix: grids and padding

---

apps/web/src/components/agents/list.tsx
apps/web/src/components/audit/AuditFilters.tsx
apps/web/src/components/audit/AuditTable.tsx
apps/web/src/components/audit/list.tsx
apps/web/src/components/common/Table.tsx
apps/web/src/components/integrations/list/installed.tsx
apps/web/src/components/integrations/list/marketplace.tsx
apps/web/src/components/triggers/list.tsx

Fix: Table styles

---

apps/web/src/components/common/Table.tsx

Fix min height

---

apps/web/src/components/settings/agent.tsx
apps/web/src/components/toolsets/header.tsx
apps/web/src/components/toolsets/index.tsx
apps/web/src/components/toolsets/selector.tsx
packages/ui/src/components/checkbox.tsx

Change agent tools selector UX

refactor: improvements on agent tools

---

apps/web/src/components/sidebar/index.tsx

fix cursor pointer

---

apps/api/src/api.ts
apps/api/src/api/integrations/api.ts
apps/api/src/api/members/api.ts
apps/api/src/api/members/invites.md
apps/api/src/api/members/invitesUtils.ts
apps/api/src/api/teams/api.ts
apps/api/src/auth/assertions.ts
apps/api/src/auth/index.ts
apps/api/src/db/schema.ts
apps/api/src/utils/context.ts
apps/web/package.json
apps/web/src/components/common/InviteTeamMembersDialog.tsx
apps/web/src/components/invites/index.tsx
apps/web/src/components/layout.tsx
apps/web/src/components/settings/members.tsx
apps/web/src/components/sidebar/TeamSelector.tsx
apps/web/src/components/sidebar/index.tsx
apps/web/src/main.tsx
packages/sdk/src/crud/mcp.ts
packages/sdk/src/crud/members.ts
packages/sdk/src/hooks/api.ts
packages/sdk/src/hooks/members.ts
packages/ui/src/components/sonner.tsx

feat: invites

---

apps/web/src/components/integrations/detail/context.ts
apps/web/src/components/integrations/detail/edit.tsx
apps/web/src/components/integrations/detail/form.tsx

fix: edit integrations

---

apps/web/src/components/chat/Markdown.tsx

feat(chat markdown): render a nice table when model outputs one

---

apps/web/package.json
apps/web/vite.config.ts

This reverts commit 54720f9185351021b34b20bb855ec64e213fccbf.

Revert "chore: switch vite + rollup to vite + rolldown (#254)"

---

apps/web/src/components/sales-deck/deck.tsx
apps/web/src/main.tsx

Feat: Add sales deck document

---

apps/web/src/components/chat/ChatInput.tsx
apps/web/src/components/chat/RichText.tsx
apps/web/src/components/chat/context.tsx

This PR:
1. Moves the file upload from form submit into onImageDrop
2. Disables the submit form button when is uploading file
3. Enables file drop and file pasting into the form element

chore: Upload to server eagerly

---

apps/web/src/components/settings/chat.tsx
apps/web/src/components/toolsets/header.tsx
apps/web/src/components/toolsets/index.tsx

- Fix tools selector on Integrations chat
- Better error UI + manage shortcut (goes to the integration page)

fix: add manage tools and selector to the integrations ui

---

README.md
apps/web/src/components/triggers/list.tsx
apps/web/src/components/triggers/triggerCard.tsx
apps/web/src/components/triggers/triggerDetails.tsx
apps/web/src/components/triggers/triggerToggle.tsx
packages/sdk/src/crud/trigger.ts
packages/sdk/src/hooks/trigger.ts
packages/sdk/src/mcp/index.ts
packages/sdk/src/mcp/triggers/api.ts
packages/sdk/src/models/trigger.ts
packages/sdk/src/storage/supabase/schema.ts
supabase/migrations/20250516185217_add_active-column_triggers.sql

Feat: Add toggle triggers

---

packages/ai/src/triggers/services.ts

we lost this commit on the migration: https://github.com/deco-cx/webdraw/commit/b741555103d861da016a9c01bebfb6064caaa23c

fix: webhook creation with output tool

---

apps/web/src/components/invites/index.tsx
apps/web/src/components/sidebar/index.tsx

Invite link is back

---

apps/web/src/components/triggers/cronDetails.tsx
apps/web/src/components/triggers/cronTriggerForm.tsx
apps/web/src/components/triggers/list.tsx
apps/web/src/components/triggers/triggerCard.tsx
apps/web/src/components/triggers/triggerType.tsx
packages/ai/src/triggers/cron.ts
packages/ai/src/triggers/services.ts
packages/ai/src/triggers/trigger.ts
packages/sdk/src/mcp/triggers/api.ts
packages/sdk/src/models/trigger.ts

Feat: Normalize trigger schema

Feat: Normalize trigger schema

---

.github/workflows/deploy-api.yaml

chore: add AWS credentials and bucket name to deploy API workflow

---

apps/web/src/components/agent/edit.tsx
apps/web/src/components/agents/list.tsx
apps/web/src/components/dock/index.tsx
apps/web/src/components/integrations/detail/edit.tsx
apps/web/src/components/settings/page.tsx

Splits the view into nice tabs when openning the docked layout

chore: open with split view

---

apps/web/src/components/layout.tsx

Keep sidebar state. 
If you close, next refresh sidebar will be closed. 
If you open, next refresh sidebar will be open

chore: persist sidebar state | QoL

---

packages/sdk/src/storage/supabase/schema.ts
supabase/migrations/20250520142229_add_profile_number.sql

- Updated type definitions in `schema.ts` to remove unnecessary semicolons and ensure consistent formatting.
- Added new columns `phone` and `phone_verified_at` to the `profiles` table in the migration file for enhanced user profile management.

Refactor Supabase schema types for consistency and clarity

---

apps/api/src/middlewares/context.ts
apps/web/src/components/chat/ChatInput.tsx
packages/sdk/package.json
packages/sdk/src/crud/fs.tsx
packages/sdk/src/hooks/api.ts
packages/sdk/src/hooks/fs.ts
packages/sdk/src/hosts.ts
packages/sdk/src/mcp/context.ts
packages/sdk/src/mcp/fs/api.ts
packages/sdk/src/mcp/index.ts

This PR bings back FS more focused on the blob storage. The blob storage is part of the workspace MCP.
The blob storage has metadata capabilties and some basic crud APIs. Also, the upload file button is using this new API.
The goal is to use this as part of our agent knowledge base.

chore: FS Uploads

---

.github/workflows/deploy-api.yaml
apps/api/src/middlewares/context.ts
apps/web/src/components/chat/ChatInput.tsx
packages/sdk/package.json
packages/sdk/src/crud/fs.tsx
packages/sdk/src/hooks/api.ts
packages/sdk/src/hooks/fs.ts
packages/sdk/src/hosts.ts
packages/sdk/src/mcp/context.ts
packages/sdk/src/mcp/fs/api.ts
packages/sdk/src/mcp/index.ts

chore: add env vars

---

apps/web/src/components/agent/WhatsAppButton.tsx

fix: sound only deco

---

apps/web/src/components/agent/WhatsAppButton.tsx

Fix only deco

---

apps/web/src/components/agent/BreadcrumbSegment.tsx
apps/web/src/components/chat/ChatInput.tsx
packages/sdk/src/mcp/agents/api.ts

If you try to access an thread where agent is deleted, an error occours.
This error happen because the TOOL CRUD is not returning correctly the Custom error.
Before:
After:

Fix: Error on not found agent

---

apps/web/src/components/sidebar/index.tsx
packages/ai/src/agent.ts
packages/sdk/src/crud/thread.ts
packages/sdk/src/hooks/thread.ts
packages/sdk/src/mcp/index.ts
packages/sdk/src/mcp/threads/api.ts

Feat: Add Rename and delete threads
The delete action only deletes from view, not from database
https://github.com/user-attachments/assets/e17a61f0-1e69-4ae3-a512-e8f3950582be

Feat: Add Rename and delete threads

---

apps/api/main.ts
apps/api/src/api.ts
packages/sdk/src/fetch.ts

This allow local calls to be authorized (bypass)

Allow for local calls

---

apps/web/src/components/agent/chat.tsx

feat: enabling whatsapp button for all workspaces

---

apps/api/src/auth/index.ts
packages/sdk/src/mcp/context.ts
packages/sdk/src/mcp/profiles/api.ts

Revert "fix: check if user is anonymous before get profile"

---

packages/sdk/src/hooks/agent.ts
packages/sdk/src/mcp/agents/api.ts

Feat: Delete triggers from agent on agent delete

Feat: Delete triggers from agent on agent delete

---

apps/web/src/components/agents/list.tsx
apps/web/src/components/common/Avatar.tsx
apps/web/src/components/integrations/detail/form.tsx
apps/web/src/components/integrations/list/common.tsx
apps/web/src/components/settings/agent.tsx
apps/web/src/hooks/usePersistedDirtyForm.ts

Feat: Add upload to FS on agent avatar and integration icon
Any UI change

Feat: Add upload to FS on agent avatar and integration icon

---

apps/web/src/components/chat/ChatInput.tsx
apps/web/src/components/common/Avatar.tsx
apps/web/src/components/integrations/detail/form.tsx
apps/web/src/components/integrations/list/common.tsx
apps/web/src/components/settings/agent.tsx
apps/web/src/utils/path.ts
packages/sdk/src/crud/fs.tsx

Feat: use useFile only when is filepath icon and avatar

Feat: use useFile only when is filepath icon and avatar

---

.github/workflows/claude.yml
packages/ai/src/models.ts
packages/ai/src/triggers/webhook.ts

fix: claude model id and options on webhooks

---

apps/web/src/components/triggers/webhookDetails.tsx
packages/sdk/src/mcp/triggers/api.ts
packages/sdk/src/models/trigger.ts

fix: webhook url builder

---

packages/sdk/src/mcp/context.ts

fix: use same context

---

packages/ai/package.json
packages/ai/src/agent.ts
packages/ai/src/triggers/webhook.ts
packages/ai/src/types.ts
packages/sdk/src/models/agent.ts

- Added @mastra/voice-openai dependency to package.json.
- Implemented voice functionality in AIAgent, allowing for audio transcription and speech synthesis using OpenAI's models.
- Updated webhook trigger to support audio input via base64 encoding.

feat: integrate OpenAI voice capabilities into AIAgent

---

apps/web/src/components/triggers/addTriggerModal.tsx
apps/web/src/components/triggers/agentTriggers.tsx
apps/web/src/components/triggers/cronTriggerForm.tsx
apps/web/src/components/triggers/list.tsx
apps/web/src/components/triggers/triggerActions.tsx
apps/web/src/components/triggers/triggerDetails.tsx
apps/web/src/components/triggers/webhookTriggerForm.tsx
apps/web/src/main.tsx
packages/sdk/src/crud/trigger.ts
packages/sdk/src/hooks/trigger.ts
packages/sdk/src/mcp/index.ts
packages/sdk/src/mcp/triggers/api.ts

Revert "Feat: Add Edit trigger"

---

apps/web/src/components/triggers/agentTriggers.tsx
apps/web/src/components/triggers/cronTriggerForm.tsx
apps/web/src/components/triggers/list.tsx
apps/web/src/components/triggers/triggerActions.tsx
apps/web/src/components/triggers/triggerDetails.tsx
apps/web/src/components/triggers/triggerModal.tsx
apps/web/src/components/triggers/webhookTriggerForm.tsx
apps/web/src/main.tsx
packages/sdk/src/crud/trigger.ts
packages/sdk/src/hooks/trigger.ts
packages/sdk/src/mcp/index.ts
packages/sdk/src/mcp/triggers/api.ts

Revert "Revert "Feat: Add Edit trigger""

---

apps/web/src/components/triggers/addTriggerModal.tsx
apps/web/src/components/triggers/agentTriggers.tsx
apps/web/src/components/triggers/cronTriggerForm.tsx
apps/web/src/components/triggers/list.tsx
apps/web/src/components/triggers/triggerActions.tsx
apps/web/src/components/triggers/triggerDetails.tsx
apps/web/src/components/triggers/webhookTriggerForm.tsx
apps/web/src/main.tsx
packages/sdk/src/crud/trigger.ts
packages/sdk/src/hooks/trigger.ts
packages/sdk/src/mcp/index.ts
packages/sdk/src/mcp/triggers/api.ts

Revert "Revert "Revert "Feat: Add Edit trigger"""

---

packages/ai/src/agent.ts
packages/sdk/src/models/agent.ts

- Removed the voice settings for text-to-speech and speech-to-text from the AIAgent class initialization.

fix: remove voice configuration from AIAgent initialization

---

apps/web/src/components/audit/AuditFilters.tsx
apps/web/src/components/audit/list.tsx
packages/sdk/src/hooks/audit.ts
packages/ui/src/components/combobox.tsx

- Added a new Combobox component for improved agent selection.
- Replaced the Select component in AuditFilters with the new Combobox for better user experience.
- Updated AuditListContent to handle loading state for audit events.
https://github.com/user-attachments/assets/a5f0b094-9ad8-4bb6-9388-8316dcc73687

chore: implement Combobox component and update AuditFilters to use it

---

apps/web/src/components/agent/WhatsAppButton.tsx
apps/web/src/components/agent/chat.tsx

- Integrated WhatsAppButton into the chat dropdown menu for improved accessibility.
- Updated WhatsAppButton to support mobile layout and conditional rendering based on the device type.
- Refactored button rendering logic to streamline user interaction for both mobile and desktop users.

chore: add WhatsApp button to chat dropdown and enhance mobile support

---

packages/sdk/src/hooks/mcp.ts

feat: adding google sheets in oauth flow

---

packages/ai/src/tools.ts
packages/sdk/src/mcp/triggers/api.ts

Feat: Add WHO_AM_I innate tool

Feat: Add WHO_AM_I innate tool

---

apps/web/src/components/agent/audit.tsx
apps/web/src/components/agent/edit.tsx
apps/web/src/components/audit/AuditTable.tsx
apps/web/src/components/audit/detail.tsx
apps/web/src/components/audit/list.tsx
apps/web/src/components/sidebar/index.tsx
apps/web/src/components/sidebar/settings.tsx
apps/web/src/components/triggers/triggerDetails.tsx
packages/sdk/src/crud/thread.ts
packages/sdk/src/hooks/api.ts
packages/sdk/src/hooks/audit.ts

Add history view for each history

chore: History view for agents

---

packages/ai/src/agent.ts
packages/sdk/src/hooks/mcp.ts

feat: googlegmail

---

apps/api/src/api.ts
apps/web/src/components/toolsets/binding-selector.tsx
apps/web/src/components/triggers/cronTriggerForm.tsx
apps/web/src/components/triggers/webhookTriggerForm.tsx
packages/ai/src/agent.ts
packages/ai/src/triggers/cron.ts
packages/ai/src/triggers/services.ts
packages/ai/src/triggers/trigger.ts
packages/ai/src/triggers/webhook.ts
packages/ai/src/types.ts
packages/sdk/package.json
packages/sdk/src/crud/agent.ts
packages/sdk/src/hooks/tools.ts
packages/sdk/src/mcp/agents/api.ts
packages/sdk/src/mcp/bindings/README.md
packages/sdk/src/mcp/bindings/binder.ts
packages/sdk/src/mcp/bindings/index.ts
packages/sdk/src/mcp/bindings/trigger.ts
packages/sdk/src/mcp/bindings/utils.ts
packages/sdk/src/mcp/context.ts
packages/sdk/src/mcp/index.ts
packages/sdk/src/mcp/integrations/api.ts
packages/sdk/src/mcp/stub.ts
packages/sdk/src/mcp/triggers/api.ts
packages/sdk/src/models/trigger.ts
packages/sdk/src/storage/supabase/client.ts
packages/sdk/src/storage/supabase/schema.ts
supabase/migrations/20250523145332_trigger-binding.sql

Revert "Revert "Bindings!""

---

packages/sdk/src/constants.ts

improve prompt

---

apps/web/src/components/agent/chats.tsx
apps/web/src/components/chat/context.tsx
apps/web/src/components/integrations/detail/edit.tsx
apps/web/src/components/settings/chat.tsx
packages/ai/src/agent.ts
packages/sdk/src/hooks/thread.ts

https://www.loom.com/share/b11a6ce9216f4249841bf002f9372f60?sid=952c62fa-af88-4dba-a303-e28a616d3ac1

feat: client side tools

---

apps/web/src/components/settings/chat.tsx
apps/web/src/components/sidebar/index.tsx

after some quick use with my users I've figured out nobody clicks on save, so I'll auto save for them

chore: client side tools

---

apps/web/src/components/audit/detail.tsx

fix: truncate breadcrumb

---

apps/web/src/components/chat/ToolsButton.tsx
apps/web/src/components/chat/context.tsx
apps/web/src/components/integrations/detail/edit.tsx
apps/web/src/components/integrations/list/marketplace.tsx
apps/web/src/components/settings/chat.tsx
apps/web/src/hooks/useTools.ts
packages/sdk/src/constants.ts
packages/sdk/src/hooks/mcp.ts
packages/sdk/src/hooks/thread.ts

drop automatic message from integration setup
https://www.loom.com/share/49fd7f94994b4819b50ad1bb78ba7290?sid=424b08a6-2914-46da-a9fb-b3c2917958a9

fix: Improve integration setup

---

apps/web/src/components/settings/integrations.tsx

add description

---

apps/web/src/components/agent/edit.tsx
apps/web/src/components/dock/index.tsx
apps/web/src/components/settings/prompt.tsx

improve golden layout

---

apps/web/src/components/chat/context.tsx
apps/web/src/components/common/Avatar.tsx
packages/sdk/src/hooks/thread.ts

Keep threads in sync with optimistic threads

fix: optimistic thread

---

apps/web/src/components/integrations/list/marketplace.tsx

feat(marketplace): show first party integrations first

---

apps/web/src/components/JSONSchemaForm/Form.tsx
apps/web/src/components/JSONSchemaForm/components/ArrayField.tsx

feat: ArrayField for form

---

apps/web/src/components/common/InviteTeamMembersDialog.tsx
apps/web/src/components/common/RolesDropdown.tsx
apps/web/src/components/settings/members.tsx
packages/sdk/src/auth/policy.ts
packages/sdk/src/crud/members.ts
packages/sdk/src/hooks/members.ts
packages/sdk/src/mcp/index.ts
packages/sdk/src/mcp/members/api.ts
supabase/migrations/20250521202707_add-update-member-policies.sql

Allow change member role and multiple roles in invites
member role:
invite:

feat: change member role

---

packages/ui/src/components/combobox.tsx

fix(ui): improve combobox search to use labels instead of values

---

packages/sdk/src/memory/libsql.ts

fix: update thread's "updatedAt" when new messages are saved

---

apps/web/src/components/toolsets/description.tsx
apps/web/src/components/toolsets/selector.tsx
packages/ui/src/components/checkbox.tsx

chore(ui): better integrations list

---

packages/sdk/src/crud/wallet.ts
packages/sdk/src/hooks/wallet.ts
packages/sdk/src/mcp/wallet/api.ts

chore: remove paywall for behring demo

---

packages/ai/src/agent/wallet.ts

start workspace with 10 dolars

---

apps/web/src/main.tsx

Reverts deco-cx/chat#451
https://github.com/user-attachments/assets/2bdb1961-43ff-471c-8afd-7bdb778c28a2

Revert "avoid redirect twice"

---

packages/ai/src/agent.ts

fix: bring back chunking

---

packages/ai/src/agent/ai-message.ts

let's try this fix and see what happens. I tested some basic flows, like image description and thread memory.

fix: makes memory work for both whatsapp and web

---

apps/web/src/components/settings/channels.tsx
packages/sdk/src/crud/channels.ts
packages/sdk/src/mcp/bindings/channels.ts
packages/sdk/src/mcp/bindings/utils.ts
packages/sdk/src/mcp/index.ts

Add list channel func

---

apps/web/src/components/integrations/apps.ts
apps/web/src/components/integrations/connection-detail.tsx

fix(connections): newly created custom connections with single instance appearing as unknown

---

apps/web/src/components/prompts/rich-text.tsx

Fix: Ignore HTML parsing

---

apps/api/wrangler.toml

Revert "Remove decopage routing"

---

packages/ai/src/utils/create-tool.ts

This decreases the number of tokens used by llm

chore: reduce the number of tokens

---

packages/ai/src/utils/create-tool.ts

chore: reduce tokens

---

packages/sdk/src/hooks/mcp.ts

add google drive

---

apps/web/src/components/agent/edit.tsx

fix: await for agent

---

packages/sdk/src/hooks/mcp.ts

add google docs

---

packages/cli/cli.ts
packages/cli/deno.json
packages/cli/src/config.ts
packages/cli/src/mcp.ts
packages/cli/src/typings.ts

you can use
`deco gen > env.ts`

Adds a `deco gen` command that generate typings

---

apps/web/src/components/chat/chat-input.tsx
packages/ai/src/agent.ts
packages/ai/src/tools.ts

Revert "feat: add TRANSCRIBE_AUDIO native tool for audio transcription"

---

apps/web/src/components/agent/edit.tsx
apps/web/src/components/chat/context.tsx
apps/web/src/components/settings/advanced.tsx
apps/web/src/components/sidebar/footer.tsx
apps/web/src/hooks/use-user-preferences.ts
packages/ai/package.json
packages/ai/src/agent.ts
packages/ai/src/triggers/webhook.ts
packages/ai/src/types.ts
packages/sdk/src/constants.ts
packages/sdk/src/memory/memory.ts
packages/sdk/src/models/agent.ts

This PR introduces working memory integration to enhance agent context retention and improve interaction coherence. 
- Working Memory Storage: Supports markdown or JSON schema for flexible memory representation.
- Message History: Stores recent messages per agent, enabling contextual awareness.
- Semantic Recall: Facilitates intelligent retrieval of relevant past interactions.
- Links to mastra docs about each feature on the UI
Since memory is tied to individual threads, it cannot be dynamically activated or modified within the same thread. Users must activate memory in a new thread to apply changes.

feat: New memory options

---

apps/web/index.css
apps/web/src/components/agent/chat.tsx
apps/web/src/components/agent/edit.tsx
apps/web/src/components/agent/preview.tsx
apps/web/src/components/agents/list.tsx
apps/web/src/components/audit/detail.tsx
apps/web/src/components/audit/list.tsx
apps/web/src/components/dock/index.tsx
apps/web/src/components/dock/views-button.tsx
apps/web/src/components/integrations/breadcrumb.tsx
apps/web/src/components/integrations/connection-detail.tsx
apps/web/src/components/layout.tsx
apps/web/src/components/prompts/detail/detail.tsx
apps/web/src/components/prompts/list/list.tsx
apps/web/src/components/settings/page.tsx
apps/web/src/components/triggers/list.tsx
apps/web/src/components/triggers/trigger-details.tsx
apps/web/src/utils/react-prepend-portal.ts

feat: new views ui

---

apps/web/src/components/prompts/rich-text/markdown.tsx
apps/web/src/components/prompts/rich-text/raw.tsx

Fix: Prompt save changes

---

packages/sdk/src/mcp/knowledge/api.ts
packages/sdk/src/memory/memory.ts

fix: knowledge base

---

apps/api/src/api.ts
apps/web/src/components/chat/tool-message.tsx
apps/web/src/components/chat/utils/parse.ts
apps/web/src/components/integrations/apps.ts
apps/web/src/components/settings/integrations.tsx
packages/ai/src/agent.ts
packages/ai/src/agents/handoff.ts
packages/ai/src/types.ts
packages/sdk/src/mcp/agent/api.ts
packages/sdk/src/mcp/index.ts
packages/sdk/src/mcp/integrations/api.ts
packages/sdk/src/models/agent.ts

feat: agent as mcp

---

apps/api/src/api.ts
packages/runtime/package.json
packages/sdk/src/mcp/context.ts
packages/sdk/src/mcp/integrations/api.ts

fix: cli invoke agents

---

apps/web/src/components/agent/hooks/use-agent-knowledge.ts
packages/sdk/src/mcp/knowledge/api.ts

When failing add file to knowledge base, remove file and remove from knowledge. Also show a toast.

fix: improve UX when failing to upload file to knowledge base

---

packages/sdk/src/hooks/workflows.ts

do not pull for errored

---

packages/sdk/src/mcp/knowledge/api.ts

fix docIds from knowledge files and remove knowledge file from UI

fix: docIds from knowledge files

---

apps/web/src/components/chat/chat-markdown.tsx

fix horizontal scroll for code blocks

---

apps/web/package.json
apps/web/src/main.tsx
apps/web/vite.config.ts

Use vite pwa plugin to solve dynamic import error cross deployment

fix: add vite-plugin-pwa to solve dynamic import error

---

apps/web/src/components/prompts/detail/form.tsx
apps/web/src/components/prompts/detail/history.tsx
apps/web/src/components/prompts/rich-text/index.tsx

use mentions

---

apps/web/index.css
apps/web/src/components/agents/list.tsx
apps/web/src/components/chat/model-selector.tsx
apps/web/src/components/chat/tools/agent-card.tsx
apps/web/src/components/common/view-mode-switcher.tsx
apps/web/src/components/dock/views-button.tsx
apps/web/src/components/integrations/connection-detail.tsx
apps/web/src/components/prompts/rich-text/extensions/mentions/mention-node.tsx
apps/web/src/components/prompts/rich-text/extensions/suggestions/dropdown.tsx
apps/web/src/components/settings/advanced.tsx
apps/web/src/components/settings/agent-profile.tsx
apps/web/src/components/settings/general.tsx
apps/web/src/components/settings/integrations.tsx
apps/web/src/components/theme.tsx
apps/web/src/components/toolsets/selector.tsx
apps/web/src/components/triggers/agent-triggers.tsx
packages/sdk/src/mcp/hosting/api.ts
packages/sdk/src/mcp/integrations/api.ts
packages/ui/src/components/button.tsx
packages/ui/src/components/command.tsx
packages/ui/src/components/form.tsx
packages/ui/src/components/input.tsx

- Updated color tokens in all product, specially in tabs and agent views
- Removed lucide-icons use in search and replaced with material design for consistency

fix(ui): update correct color tokens

---

apps/web/index.css
apps/web/src/components/integrations/connection-detail.tsx
apps/web/src/components/prompts/rich-text/index.tsx
packages/sdk/src/hooks/mcp.ts
packages/ui/src/styles/global.css

- Updated scrollbar to show on hover and use color token
- Update a few color tokens around the product

fix(ui): scrollbar show on hover and use color token

---

.cursor/rules/data-flow.mdc
.cursor/rules/wallet.mdc

To improve our AIX (AI development experience), I'm adding two new [Cursor rules](https://docs.cursor.com/context/rules):
- **Data Flow** describing tools, MCP servers, React Query.
- **Wallet** talking about our credit system.
I asked Cursor to create both of them based on @viktormarinho's work on #710
One interesting aspect is that I used this type of rule which is not included in every request but **the agent automatically requests it** if the current task is related to a Description field. This seems interesting.
(Check the Description)
And it works!
https://github.com/user-attachments/assets/780068a9-87c0-4bde-8ff0-9cca9d46fdfa

Adding rules for Data Flow and Wallet

---

packages/sdk/src/hooks/mcp.ts

https://www.loom.com/share/f96a20b8744b4402b376d1489129491a

Add Spotify oAuth support

---

apps/web/src/components/settings/advanced.tsx
apps/web/src/components/settings/channels.tsx

chore: change channels UI to be less explosive

---

apps/web/src/components/settings/advanced.tsx
packages/ai/src/agent.ts
packages/sdk/src/models/agent.ts
packages/sdk/src/storage/supabase/schema.ts
supabase/migrations/20250707180935_add_temperature_to_agent.sql

feat: agent temperature setting

---

apps/web/src/components/chat/chat-markdown.tsx
apps/web/src/components/chat/tool-message.tsx

fix css mobile

---

apps/web/src/components/common/table/table-cells.tsx

fix: integration avatar size

---

apps/web/src/components/chat/chat-message.tsx

fix css to render image in chat

---

packages/cli/cli.ts
packages/cli/src/config.ts
packages/cli/src/create.ts
packages/cli/src/utils/prompt-mcp-install.ts

chore: prompt user on dev

---

packages/sdk/src/constants.ts

Add Gemini 2.5 Flash Lite

---

packages/cli/cli.ts
packages/cli/deno.json
packages/cli/src/config.ts
packages/cli/src/configure.ts
packages/cli/src/create.ts
packages/cli/src/utils/prompt-integrations.ts
packages/cli/src/utils/prompt-mcp-install.ts
packages/cli/src/utils/prompt-workspace.ts
packages/cli/src/utils/slugify.ts

feat: Select integration from the deco cli

---

packages/sdk/src/mcp/wallet/well-known.ts

chore(wallet): remove unused trial credits from well known wallets

---

packages/ai/src/agent/llm-provider.ts

add openrouter metadata so we show on the most used apps

chore: add openrouter metadata

---

packages/cli/deno.json
packages/cli/src/config.ts
packages/cli/src/utils/prompt-ide-setup.ts

fix cli publish. Apparently deno didn't release the whole thing

---

SELF_HOST_pt-BR.md

O deco.chat é uma plataforma de criação de agentes de IA construída sobre uma
arquitetura moderna baseada em **Cloudflare Workers**. Esta escolha tecnológica
oferece vantagens significativas em termos de performance, escalabilidade e
facilidade de deployment.
- **TypeScript**: Linguagem base para todo o desenvolvimento
- **Cloudflare Workers**: Runtime baseado em Web Standards
- **React 19**: Interface do usuário moderna
- **Deno**: Gerenciamento de dependências e ferramentas de desenvolvimento
- **Vite**: Build system otimizado
O deco.chat utiliza o **workerd**, o runtime open source que alimenta o
Cloudflare Workers. Como descrito pela própria Cloudflare, o workerd é
"projetado especificamente para servidores" e oferece **APIs Web padrão** sempre
que possível, incluindo Fetch, URL, …

Add self hosting doc

---

apps/api/src/auth/index.ts
apps/web/src/components/login/index.tsx
apps/web/src/components/login/magic-link.tsx
apps/web/src/components/login/providers.tsx

fix: login with email (magiclink)

---

packages/cli/deno.json
packages/cli/src/config.ts
packages/cli/src/create.ts

fix(cli): `deco create` wrangler config for templates that have nested packages

---

packages/sdk/src/mcp/ai/api.ts
packages/sdk/src/mcp/wallet/well-known.ts

- Added `hasCustomKey` option to `createLLMUsageTransaction` for conditional wallet handling.
- Updated `processTransaction` to adjust usage metrics based on the presence of a custom key.
- Modified `setupLLMInstance` to return both LLM and configuration.
- Introduced `llmVaultCredits` method in `WellKnownWallets` for better wallet management.

feat(api): enhance LLM transaction handling with custom key support

---

apps/web/src/components/settings/usage/stacked-bar-chart.tsx
apps/web/src/components/sidebar/footer.tsx
packages/ui/src/components/sidebar.tsx

small fix ui of team balance label

---

apps/web/src/components/workflows/list.tsx

fix ux in workflow empty state. from there the user has nowhere to go

show cli command in workflow's empty state

---

docs/view/src/components/ui/Navigation.tsx
docs/view/src/components/ui/RenderDocument.astro
docs/view/src/components/ui/Step.tsx
docs/view/src/components/ui/StepGroup.tsx
docs/view/src/components/ui/TableOfContents.astro
docs/view/src/config/site.ts
docs/view/src/content/en/cli-reference.mdx
docs/view/src/content/en/getting-started.mdx
docs/view/src/content/en/guides/getting-started.mdx
docs/view/src/content/en/reference/faq.mdx
docs/view/src/layouts/DocsLayout.astro
docs/view/src/pages/[locale]/[...slug].astro
docs/view/src/styles/global.css
docs/view/src/utils/navigation.ts

- Edit button to edit .md inside repo
- Steps components
- deco init -> deco create
- layout fix
- navigation

docs: components, layout, edit button, update to deco create

---

apps/api/main.ts
apps/api/src/api.ts
apps/api/src/durable-objects/workspace-database.ts
apps/api/src/utils/context.ts
apps/api/wrangler.toml
packages/ai/src/agent.ts
packages/ai/src/triggers/trigger.ts
packages/sdk/src/mcp/context.ts
packages/sdk/src/mcp/databases/api.ts
packages/sdk/src/mcp/databases/d1.ts
packages/sdk/src/mcp/groups.ts
packages/sdk/src/mcp/hosting/api.ts
packages/sdk/src/mcp/index.ts

Use sqlite-in-do in favor of D1
D1 itself is built on top of sqlite-in-do but it adds some network latency compared to DO approach. 
reference: https://blog.cloudflare.com/sqlite-in-durable-objects/
It should add reliability and improve the overall latency of the system

Sqlite-in-do

---

packages/sdk/src/mcp/agent/api.ts

This PR makes the generate tool to accept parts. With this we can pass images and other files to the object generation method

feat: GENERATE OBJECT accept parts

---

packages/sdk/src/mcp/integrations/api.ts

provisional fix for integration update

---

packages/runtime/jsr.json
packages/runtime/package.json
packages/runtime/src/mcp.ts

change json-schema-to-zod library

---

apps/api/src/api.ts
apps/web/index.css
apps/web/src/components/agent/chat.tsx
apps/web/src/components/decopilot/index.tsx
apps/web/src/components/dock/index.tsx
apps/web/src/components/dock/views-button.tsx
apps/web/src/components/layout.tsx
apps/web/src/components/settings/usage/threads-table.tsx
apps/web/src/components/sidebar/footer.tsx
apps/web/src/hooks/use-user-preferences.ts
apps/web/src/utils/react-prepend-portal.ts
packages/sdk/src/constants.ts
packages/sdk/src/mcp/threads/api.ts

Creates a docked chat that is enable via feature flag

chore: Docked chat

---

apps/web/src/components/chat/context-resources.tsx
packages/sdk/src/index.ts
packages/sdk/src/utils/index.ts

Enhance ContextResources component by integrating better display names for integrations and adding agents data retrieval. Update SDK exports to include utility functions for integration display names.
Before/after

feat: ContextResources

---

apps/web/src/components/chat/chat-input.tsx
apps/web/src/components/chat/context-resources.tsx

The [@ PR](https://github.com/deco-cx/chat/pull/982) removed the way we add attachments to the submit function, I am fixing it.

Fix: restore attachments on submit.

---

packages/runtime/jsr.json
packages/runtime/src/proxy.ts

fix: use options.connection if it is an object

---

apps/web/src/components/views/list.tsx
packages/sdk/src/hooks/api.ts
packages/sdk/src/hooks/teams.ts

improve how we fetch views

---

packages/cli/package.json
packages/cli/src/commands/hosting/deploy.ts

fix(cli): send .sql files on deployment

---

packages/ai/src/triggers/trigger.ts

Addresses this message:
How's this even building? I have no idea

fix: build message error log

---

packages/sdk/src/mcp/context.ts

rollback superfrete to turso

---

apps/web/src/components/integrations/connection-detail.tsx
apps/web/src/components/sidebar/index.tsx
apps/web/src/components/views/list.tsx
packages/sdk/src/crud/teams.ts
packages/sdk/src/mcp/context.ts
packages/sdk/src/mcp/teams/api.ts

https://github.com/user-attachments/assets/524cfd01-6321-497d-a699-4729692d1ae9

group custom views by mcp

---

packages/sdk/src/mcp/databases/migration.ts

remove from denylist

---

packages/sdk/src/hooks/mcp.ts

added slides to well known integrations

---

packages/cli/package.json
packages/cli/src/lib/config.ts
packages/create-deco/package.json
packages/sdk/src/mcp/contracts/api.ts

* bump deco-cli version to 0.16.2
* bump create-deco version to 1.0.3
* add optional description field to DecoBindingSchema

chore: update package versions and enhance DecoBindingSchema (#1083)

---

apps/web/src/components/decopilot/index.tsx

It was one-thread only, and the context was getting big

generate random threadId

---

apps/web/src/components/decopilot/index.tsx

remove additional tools

---

apps/web/src/components/chat/chat-input.tsx

fix stop button

---

packages/ai/src/agent.ts

remove tack event for testing speed

---

packages/sdk/src/crud/teams.ts

fix cors error when calling a different app

fix: views bindings list

---

apps/web/src/components/apps/auth.tsx

It was getting workspace_hint from the owner of the project, not considering in what workspace it was opened.

get workspace hint from parent

---

packages/runtime/jsr.json
packages/runtime/src/mcp-client.ts

Addresses 
https://github.com/modelcontextprotocol/typescript-sdk/issues/923

fix: error compiling schema errors

---

apps/web/src/components/agent/provider.tsx
docs/package.json
package.json
packages/ai/src/agent.ts
packages/sdk/src/crud/agent.ts
packages/sdk/src/hooks/agent.ts
packages/sdk/src/models/agent.ts

Removes concurrently and fix typings

fix: check

---

packages/sdk/src/mcp/tools/utils.ts

fix: workflow integration name
