apps/web/src/components/agent/chat.tsx
Before:
- When clicking on sidebar thread chat, at second time, it take some time to "navigate" (i mean select the new route). The explanation https://react.dev/reference/react/Suspense#resetting-suspense-boundaries-on-navigation
After: 
- When clicking on sidebar chat, at second time, it navigates and show load spinner
=> feat: improve open agent thread responsiveness

packages/sdk/src/constants.ts, packages/sdk/src/crud/agent.ts, packages/sdk/src/crud/fs.tsx, packages/sdk/src/crud/mcp.ts, packages/sdk/src/crud/thread.ts, packages/sdk/src/crud/user.ts, packages/sdk/src/crud/wallet.ts, packages/sdk/src/fetcher.ts, packages/sdk/src/stub.ts
- Centralize fetch logic in a reusable fetcher utility
- Add trace debug ID to all API requests for better debugging
- Unify header management across the codebase
- Remove duplicate fetch implementations
=> feat: standardize fetch and instrument with trace debug id

apps/web/src/components/agent/ChatHeader.tsx, apps/web/src/components/agent/DetailHeader.tsx, apps/web/src/components/agent/edit.tsx, apps/web/src/components/agents/hooks.ts, apps/web/src/components/agents/list.tsx, apps/web/src/components/chat/tools/AgentCard.tsx, apps/web/src/main.tsx
Refactor: Separate Agent Chat and Edit Views
Re-Introduce a dedicated /agent/:id/:threadId route and edit.tsx component for agent configuration, including settings and a chat preview.
Update the main chat view (/chat/:id/:threadId) to focus solely on conversation.
Modify ChatHeader to include buttons for creating new chats and navigating to the new agent edit view.
Create useEditAgent hook for navigating to the edit route.
Remove the openSettings option from useFocusChat and related logic.
Update agent list actions (create, duplicate) to navigate to the appropriate view (edit or chat).
Remove the docked settings panel from the main chat layout.
=> chore: bring back separate agent edit route

apps/web/src/main.tsx
Instead of rendering two react-router routes that matches `/:teamSlug?` for app workspace and settings, split into two: `/:teamSlug?` for workspace and `/:teamSlug?/settings` for settings
=> chore: improve route matching

apps/web/src/components/about/index.tsx, apps/web/src/components/agent/chat.tsx, apps/web/src/main.tsx, packages/sdk/src/constants.ts, packages/sdk/src/hooks/agent.ts
Improve index ertrypoint bundle size
main (production): ~1.200kb
branch (with changes): ~266kb only react, react-router and tailwind-merge
also could check running ` npx vite-bundle-visualizer -c vite.config.ts`
=> perf: improve entry point asset size

apps/web/src/components/chat/ModelSelector.tsx, apps/web/src/components/chat/context.tsx, apps/web/src/hooks/useUserPreferences.ts, packages/ai/src/agent.ts, packages/ai/src/schemas.ts, packages/sdk/src/constants.ts, packages/sdk/src/models/agent.ts
auto model v1 - without an algorithm backing it up. the auto model is hardcoded on the server.
seems already useful tho, because users can keep this setting and we can change server-side the best general model at the moment.
=> feat: auto model

apps/web/src/components/integrations/detail/inspector.tsx, apps/web/src/components/integrations/detail/toolCallForm.tsx
fix form submit button, where handleSubmit doesn't call callback after schema changes, remounting the component.
steps to reproduce the error:
1. open integration `i:workspace-management`
2. click to test integrations
3. choose tool `INTEGRATIONS_GET` (can be other)
4. then fill the form and submit
5. choose tool `HOSTING_APPS_LIST` or other without schema
6. press submit
expected: submit the tool call form
current behavior: does nothing
=> fix: form submission when change schema

apps/web/src/components/toolsets/single-selector.tsx, apps/web/src/components/triggers/webhookTriggerForm.tsx, packages/ai/src/agent.ts, packages/ai/src/triggers/outputTool.ts, packages/ai/src/triggers/trigger.ts, packages/ai/src/triggers/webhook.ts, packages/ai/src/utils/workspace.ts, packages/sdk/src/crud/trigger.ts, packages/sdk/src/hooks/tools.ts
You can now opt to have an `outputTool` on your webhook trigger.
This creates a way to deterministically call tools at the end of webhook calls, good for when you need to "reply" to an external system in some way.
=> feat: webhook output tool

apps/web/src/components/JSONSchemaForm/Form.tsx, apps/web/src/components/JSONSchemaForm/index.ts, apps/web/src/components/integrations/detail/toolCallForm.tsx
Render tool call button even if tool inputSchema is empty. Also change the form header
before: 
after:
=> fix: render tool call button for tools without input schema

apps/web/package.json, apps/web/vite.config.ts
Revert back this PR https://github.com/deco-cx/chat/pull/254 with the [rolldown-vite issue](https://github.com/vitejs/rolldown-vite/issues/175#issuecomment-2890196302) fixed.
=> chore: revert back rolldown-vite with patch update

apps/web/src/components/common/EmptyState.tsx, apps/web/src/main.tsx, packages/sdk/src/errors.ts, packages/sdk/src/mcp/stub.ts
Adds x-debug-trace-id to the frontend so we can look at errors on hyperdx
=> add x-debug-trace-id to the interface

apps/web/src/components/chat/ChatInput.tsx
Somehow, we can't upload files only. vercel ai sdk has some quirks that prevent this from happening. 
A temporary fix is to disable the submit button before any text is written.
Bug evidence:
=> fix: requires text for submission

apps/web/src/components/common/TableCells.tsx
- Simplified the logic for fetching team members by directly using the data from useTeamMembers.
- Ensured that members are set to an empty array if the current user is being displayed or if teamId is null.
=> fix: fix team member fetching logic in UserInfo component

apps/web/src/components/agent/edit.tsx, packages/sdk/src/hooks/audit.ts, packages/sdk/src/hooks/thread.ts
Addresses the issue when the user see some messages from some time ago. Slows down the UI, but it's worth for now. 
I'll eventually come back on this in the future
=> fix: refetch audit list and messages on every render to avoid cached messages

apps/web/src/components/agents/list.tsx
When clicking on integration badges in the agent list, users were being redirected to their personal workspace instead of staying within their current team context.
**Solution**
- Replaced useNavigate with useNavigateWorkspace hook in the IntegrationMiniature component
- Removed unused useNavigate import
- The useNavigateWorkspace hook automatically preserves the team slug from the current URL and constructs the correct path
**Changes**
- Updated apps/web/src/components/agents/list.tsx:
- Added import for useNavigateWorkspace hook
- Replaced navigate() with navigateWorkspace() in integration click handler
- Removed unused useNavigate import
**Impact**
Users will now remain in their team workspace when navigating to integration details from the agent list, providing a consistent …
=> Refactoring: Replace useNavigate with useNavigateWorkspace.

packages/sdk/src/auth/policy.ts
when remove user from team, remove the cached policies, since getUserPolicies get cached data causing security issue
=> fix: cache duration and removeAllMemberPolicies remove users cache cache

apps/api/src/app.ts, apps/api/src/apps.ts, apps/api/src/outbound.ts, apps/api/src/utils/context.ts, apps/api/wrangler.toml, packages/sdk/src/hosts.ts
This PR implements an outbound worker solution to enable secure access to tenant APIs (api.deco.chat) from dispatched workers running on *.deco.page domains. The implementation leverages Cloudflare's Outbound Workers feature to intercept and authenticate requests to our API endpoints.
Currently, dispatched workers running on *.deco.page domains cannot securely access tenant-specific APIs exposed through api.deco.chat. This creates a limitation where tenant-specific functionality cannot be accessed from the dispatched workers.
We've implemented an outbound worker pattern that:
1. Intercepts all outbound requests from dispatched workers
2. Identifies requests targeting api.deco.chat
3. Issues JWT tokens for authenticated API access
4. Proxies requests to their intended destinations …
=> Set outbound worker for *.deco.page workers

apps/web/src/components/agent/edit.tsx, apps/web/src/components/agent/preview.tsx
```
Some agents have views. Views is an array with name and url. 
For agens that have views, I want the view to be displayed in the agent screen in a new tab close to chat.
Study @layout.tsx @/dock and implement this.
```
**Before:**
**After:**
=> Show agent views

apps/web/src/components/settings/integrations.tsx, apps/web/src/components/toolsets/selector.tsx, packages/ai/src/agent.ts
**Prompt:**
```
I want to change the search mechanism here
It shouldn't search based on Integration's name, but on the integration's tools. And it should filter the tool list based on the search.
The goal is, for integrations with lots of tools, I can search by tool name to better activate/deactivate it
Plan and implement this change
```
**Before**
**After:**
=> Search integration filter tools instead

apps/web/src/components/agent/chat.tsx, apps/web/src/components/agent/edit.tsx, apps/web/src/components/sidebar/team-selector.tsx, apps/web/src/hooks/use-document-metadata.ts
Adds the open agent's properties to the page's meta, like title, description, and favicon. this helps create the correct icon when users "Add to Home Screen"
=> Add open Agent name to page Title

packages/ai/package.json, packages/ai/src/mcp.ts
Tool output schemas were being lost during the conversion from JSON Schema to Zod schemas for INNATE integrations, causing empty TypeScript interfaces to be generated by the CLI (e.g., `FS_WRITEOutput {}`).
This fix uses zod-to-json-schema to convert Zod schemas back to JSON Schema format when tools are returned through the API for type generation, ensuring that output schemas like FS_WRITE's `url` property are properly included in the generated TypeScript interfaces.
Changes:
- Add zod-to-json-schema dependency for schema conversion
- Convert Zod schemas back to JSON Schema in listToolsByConnectionType
- Preserve original JSON schemas for CLI consumption while maintaining Zod schemas for internal tool execution
> Add screenshots or a Loom …
=> fix: preserve tool output schemas for CLI type generation

apps/web/src/components/apps/auth.tsx
=> fix css on auth page
